redo calls to recipes

diff --git a/co b/co
--- a/co
+++ b/co
@@ -1,16 +1,14 @@
 #!/usr/bin/env sh
 
 key="$1"
+coPath=$(dirname $(realpath ${BASH_SOURCE[0]}))
+if [[ ! -f $coPath/recipes/$key.sh ]]
+then
+  echo "Error: Application unavailable.\n"
+  echo "Available applications:"
+  recipes=$(ls $coPath/recipes)
+  echo "$recipes" | sed -E 's/(.*)\.sh/ \1\\/' | xargs echo ""
+  exit 1
+fi
 
-case $key in
-  vim)
-    sh ./recipes/vim.sh $(realpath $2 || $(pwd)/$(basename $2) ) ${@:3}
-  ;;
-  k6)
-    if [ $# -lt 3 ]; then
-      echo "Usage: co k6 [command] [file] [...args]"
-      exit 1
-    fi
-    bash ./recipes/k6.sh $2 $(realpath $3 || $(pwd)/$(basename $3)) ${@:4}
-
-esac
+bash $coPath/recipes/$key.sh $(pwd) ${@:2}
